Aggregate Exception
System.AggregateException
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Octopus.Shared.Tests.Util.ExceptionExtensionsFixture.RaiseAggregateException(Int32 i) in ExceptionExtensionsFixture.cs:line <n>
   at Octopus.Shared.Tests.Util.ExceptionExtensionsFixture.PrettyPrint_WithStack_SingleAggregateException() in ExceptionExtensionsFixture.cs:line <n>

--Inner Exception 1--
Inner
System.Exception
   at Octopus.Shared.Tests.Util.ExceptionExtensionsFixture.<>c.<RaiseAggregateException>b__n_1() in ExceptionExtensionsFixture.cs:line <n>
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)